### ISSUE TITLE
question about the HTTP Error?

### ISSUE THREAD

**Issue by HouZhe1** [chaofengc/IQA-PyTorch#128]
Thanks for your awesome repository, I meet some network error when I try to run the examples.

/IQA-PyTorch-main$ python inference_iqa.py -m brisque -i ./ResultsCalibra/dist_dir/I03.bmp
Downloading: "https://github.com/chaofengc/IQA-PyTorch/releases/download/v0.1-weights/brisque_svm_weights.pth" to /home/houzhe/.cache/torch/hub/checkpoints/brisque_svm_weights.pth

Traceback (most recent call last):
  File "/data1/houzhe/stitch/IQA-PyTorch-main/inference_iqa.py", line 81, in <module>
    main()
  File "/data1/houzhe/stitch/IQA-PyTorch-main/inference_iqa.py", line 28, in main
    iqa_model = create_metric(metric_name, metric_mode=args.metric_mode)
  File "/data1/houzhe/stitch/IQA-PyTorch-main/pyiqa/api_helpers.py", line 11, in create_metric
    metric = InferenceModel(metric_name, as_loss=as_loss, device=device, **kwargs)
  File "/data1/houzhe/stitch/IQA-PyTorch-main/pyiqa/models/inference_model.py", line 55, in __init__
    self.net = ARCH_REGISTRY.get(network_type)(**net_opts)
  File "/data1/houzhe/stitch/IQA-PyTorch-main/pyiqa/archs/brisque_arch.py", line 154, in __init__
    self.pretrained_model_path = load_file_from_url(default_model_urls['url'])
  File "/data1/houzhe/stitch/IQA-PyTorch-main/pyiqa/utils/download_util.py", line 98, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "/home/houzhe/miniconda3/envs/IQA/lib/python3.9/site-packages/torch/hub.py", line 597, in download_url_to_file
    u = urlopen(req)
  File "/home/houzhe/miniconda3/envs/IQA/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/houzhe/miniconda3/envs/IQA/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/houzhe/miniconda3/envs/IQA/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/houzhe/miniconda3/envs/IQA/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/houzhe/miniconda3/envs/IQA/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/houzhe/miniconda3/envs/IQA/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

Then I test the network in the terminal, while it seems normal.

PING github.com (140.82.112.5) 56(84) bytes of data.
64 bytes from github.com (140.82.112.5): icmp_seq=1 ttl=38 time=302 ms
64 bytes from github.com (140.82.112.5): icmp_seq=2 ttl=38 time=302 ms
64 bytes from github.com (140.82.112.5): icmp_seq=3 ttl=38 time=301 ms
64 bytes from github.com (140.82.112.5): icmp_seq=4 ttl=38 time=302 ms
^C
--- github.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 300.595/301.541/302.275/0.605 ms

Hope to your help.

**Comment by chaofengc** [comment]
Thanks for interest. You may need a VPN if you are in mainland China for stable connection to github. Otherwise, you can also manually download the weights and put it to the corresponding path:

link: "https://github.com/chaofengc/IQA-PyTorch/releases/download/v0.1-weights/brisque_svm_weights.pth" 
path: /home/houzhe/.cache/torch/hub/checkpoints/brisque_svm_weights.pth

**Comment by HouZhe1** [comment]
> Thanks for interest. You may need a VPN if you are in mainland China for stable connection to github. Otherwise, you can also manually download the weights and put it to the corresponding path:
> 
> link: "https://github.com/chaofengc/IQA-PyTorch/releases/download/v0.1-weights/brisque_svm_weights.pth" path: /home/houzhe/.cache/torch/hub/checkpoints/brisque_svm_weights.pth

Thank you for your selfless help!
