### ISSUE TITLE
Train on new datasets

### ISSUE THREAD

**Issue by Sunnyiren** [chaofengc/IQA-PyTorch#44]
Hi, I want to use pyiqa to train and test on new dataset, but I met some problems. Except adding a new code about new dataset in ./pyiqa/data/, Is there anywhere I need to modify? Thanks a lot!

Traceback (most recent call last):
  File "pyiqa/train.py", line 242, in <module>
    train_pipeline(root_path)
  File "pyiqa/train.py", line 131, in train_pipeline
    result = create_train_val_dataloader(opt, logger)
  File "pyiqa/train.py", line 36, in create_train_val_dataloader
    train_set = build_dataset(dataset_opt)
  File "/data1/xutong/anaconda3/envs/IQA/lib/python3.8/site-packages/pyiqa/data/__init__.py", line 34, in build_dataset
    dataset = DATASET_REGISTRY.get(dataset_opt['type'])(dataset_opt)
  File "/data1/xutong/anaconda3/envs/IQA/lib/python3.8/site-packages/pyiqa/utils/registry.py", line 65, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'UWIQADataset' found in 'dataset' registry!"

**Comment by Sunnyiren** [comment]
I found my error that I modified in the wrong position. I should change the code in pyiqa in anaconda3/envs/envs-name/lib/python3.8/site-packages/pyiqa/. I will close this issue.
