### ISSUE TITLE
function takes at most 1 argument (2 given)

### ISSUE THREAD

**Issue by limco-f** [chaofengc/IQA-PyTorch#56]
hi，thanks for your project!
I'd wonder why the project reports an error when i'm calculating pi and nrqm.
I changed np.complex() to np.comlex_() because of numpy version, and then it reports "TypeError: function takes at most 1 argument (2 given)".
Here is the error.
` python inference_iqa.py -m nrqm -i ./ResultsCalibra/002_bicubic_x4.png
  0%|                                                                                                                                     | 0/1 [00:00<?, ?image/s]Traceback (most recent call last):
  File "/Users/limco/Downloads/IQA-PyTorch-main/inference_iqa.py", line 73, in <module>
    main()
  File "/Users/limco/Downloads/IQA-PyTorch-main/inference_iqa.py", line 52, in main
    score = iqa_model(img_path, ref_img_path).cpu().item()
  File "/Users/limco/Downloads/IQA-PyTorch-main/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/limco/Downloads/IQA-PyTorch-main/pyiqa/models/inference_model.py", line 75, in forward
    output = self.net(target.to(self.device))
  File "/Users/limco/Downloads/IQA-PyTorch-main/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/limco/Downloads/IQA-PyTorch-main/pyiqa/archs/nrqm_arch.py", line 443, in forward
    score = calculate_nrqm(X, self.crop_border, self.test_y_channel, self.pretrained_model_path, self.color_space)
  File "/Users/limco/Downloads/IQA-PyTorch-main/pyiqa/archs/nrqm_arch.py", line 399, in calculate_nrqm
    nrqm_result = nrqm(img, linear_param, rf_params_list)
  File "/Users/limco/Downloads/IQA-PyTorch-main/pyiqa/archs/nrqm_arch.py", line 343, in nrqm
    f2 = global_gsm(img)
  File "/Users/limco/Downloads/IQA-PyTorch-main/pyiqa/archs/nrqm_arch.py", line 247, in global_gsm
    pyr = SCFpyr_PyTorch(height=2, nbands=num_bands, device=img.device).build(img)
  File "/Users/limco/Downloads/IQA-PyTorch-main/pyiqa/matlab_utils/scfpyr_util.py", line 47, in __init__
    self.complex_fact_construct = np.power(np.complex_(0, -1), self.nbands - 1)
TypeError: function takes at most 1 argument (2 given)
`

**Comment by chaofengc** [comment]
`np.complex_` appears to be distinct from `np.complex` and only accepts one argument. I have not tested the program with various versions of numpy. The recommended approach would be to use the appropriate environment version via conda.

**Comment by limco-f** [comment]
Thanks for your reply, I will try again.

**Comment by limco-f** [comment]
I changed np.complex() to complex() and it worked successfully.
