### ISSUE TITLE
about niqe

### ISSUE THREAD

**Issue by han48614284** [chaofengc/IQA-PyTorch#61]
Hello, when I use NIQE metric, it reported the error as follows:

python inference_iqa.py -i /media/gpu/HS/SCGAN-main/test_results_pre/results_Widerface_96/ --metric_mode NR -m niqe --save_file /home/gpu/Documents/HS/niqe.txt

  0%|                                                                                                      | 0/2000 [00:00<?, ?image/s]Traceback (most recent call last):
  File "inference_iqa.py", line 73, in <module>
    main()
  File "inference_iqa.py", line 52, in main
    score = iqa_model(img_path, ref_img_path).cpu().item()
  File "/home/gpu/anaconda3/envs/pulse/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gpu/Documents/HS/IQA-PyTorch/pyiqa/models/inference_model.py", line 75, in forward
    output = self.net(target.to(self.device), **kwargs)
  File "/home/gpu/anaconda3/envs/pulse/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gpu/Documents/HS/IQA-PyTorch/pyiqa/archs/niqe_arch.py", line 446, in forward
    score = calculate_niqe(X, self.crop_border, self.test_y_channel, self.pretrained_model_path, self.color_space)
  File "/home/gpu/Documents/HS/IQA-PyTorch/pyiqa/archs/niqe_arch.py", line 179, in calculate_niqe
    niqe_result = niqe(img, mu_pris_param, cov_pris_param)
  File "/home/gpu/Documents/HS/IQA-PyTorch/pyiqa/archs/niqe_arch.py", line 133, in niqe
    cov_distparam = nancov(distparam)
  File "/home/gpu/Documents/HS/IQA-PyTorch/pyiqa/matlab_utils/functions.py", line 187, in nancov
    cov_x.append(cov(x_no_nan, rowvar=False))
  File "/home/gpu/Documents/HS/IQA-PyTorch/pyiqa/matlab_utils/functions.py", line 167, in cov
    factor = 1 / (tensor.shape[-1] - int(not bool(bias)))
**ZeroDivisionError: division by zero**
  0%|                                                                                                      | 0/2000 [00:04<?, ?image/s]

I want to know what caused that? Thank you very much!

**Comment by chaofengc** [comment]
Would you please provide example images that caused the problem ?

**Comment by han48614284** [comment]
![0_Parade_Parade_0_103_01 png_sr](https://user-images.githubusercontent.com/115164294/222406276-c5b62fba-56d6-4c72-a82c-cafa128d8e09.png)

**Comment by han48614284** [comment]
![image](https://user-images.githubusercontent.com/115164294/222406680-4bb6507a-ba9c-4da5-855d-54fd9905aba3.png)
It's the information of the image.

**Comment by chaofengc** [comment]
Thanks for your information. Bug fixed at 8d7462d.
